# Generated by Django 6.0.5 on 2026-05-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('scholarship', 'Talyp haky'), ('salary', 'Iş aýlygy'), ('freelance', 'Freelance'), ('family', 'Maşgala'), ('other', 'Beýleki')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField(help_text='Store as first day of the month')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month', '-created_at'],
            },
        ),
    ]
