# Generated by Django 6.0.5 on 2026-05-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='goal_covers/'),
        ),
    ]
